### ISSUE TITLE
Could not find a version that satisfies the requirement pyminifier==2.3.0 (from versions: 2.0, 2.1)

### ISSUE THREAD

**Issue by Starm1st** [Kalaborative/JKLMBombpartyHelper#8]
When i run pip install -r requirements.txt, i get this error code at the end, do i need an older version of python as this is older code or?
![image](https://user-images.githubusercontent.com/89106846/129816611-21b99b6d-695c-4952-a93a-0056d6be5e06.png)

**Comment by Kalaborative** [comment]
Oh, pyminifier was just to minify the code. It should be necessary to run it, sorry!
