### ISSUE TITLE
Slowing Typing speed

### ISSUE THREAD

**Issue by aznboi1011** [Kalaborative/JKLMBombpartyHelper#9]
Is there a way we can slow the typing speed?

**Comment by Kalaborative** [comment]
Are you using `auto_bot.py`? If so yes:
https://github.com/Kalaborative/JKLMBombpartyHelper/blob/fd250b6c128a1c6e1977d26a281f1c6233316c9a/auto_bot.py#L51
This line controls the various points that the `sleep` function runs in between letter types. Enter larger values to make it type slower (like `[0.5, 1.0, 0.9]` for example)
